/**:
  ros__parameters:
    imu_pub_topic: mru/imu
    frame_id: mru_frame

    connection_params:
      remote_ip: "10.0.1.20"
      data_remote_port: 7550
      data_local_port: 7551
      control_local_port: 7552

    mru_settings:
      channel: "UDP1"
      port: 7551
      ip_addr: "10.0.1.153"
      format: "MRUBIN"
      interval: 5   # Output interval in ms
      token: 21      # MRUBIN token
